name: CI Backend

on:
  pull_request:
    branches: [main]
    paths:
      - "packages/backend/**"
      - ".github/workflows/ci-backend.yml"
      - ".github/workflows/ci-backend-maintenance.yml"

jobs:
  lint-and-test:
    name: Backend quality and unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dummy step
        run: echo "Hello"
